// Code generated by mockery. DO NOT EDIT.

package service

import (
	database "auction-api/database"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuctionRepository is an autogenerated mock type for the AuctionRepository type
type AuctionRepository struct {
	mock.Mock
}

type AuctionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionRepository) EXPECT() *AuctionRepository_Expecter {
	return &AuctionRepository_Expecter{mock: &_m.Mock}
}

// CreateAuction provides a mock function with given fields: auction
func (_m *AuctionRepository) CreateAuction(auction *database.Auction) (*database.Auction, error) {
	ret := _m.Called(auction)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuction")
	}

	var r0 *database.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(*database.Auction) (*database.Auction, error)); ok {
		return rf(auction)
	}
	if rf, ok := ret.Get(0).(func(*database.Auction) *database.Auction); ok {
		r0 = rf(auction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(*database.Auction) error); ok {
		r1 = rf(auction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_CreateAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuction'
type AuctionRepository_CreateAuction_Call struct {
	*mock.Call
}

// CreateAuction is a helper method to define mock.On call
//   - auction *database.Auction
func (_e *AuctionRepository_Expecter) CreateAuction(auction interface{}) *AuctionRepository_CreateAuction_Call {
	return &AuctionRepository_CreateAuction_Call{Call: _e.mock.On("CreateAuction", auction)}
}

func (_c *AuctionRepository_CreateAuction_Call) Run(run func(auction *database.Auction)) *AuctionRepository_CreateAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.Auction))
	})
	return _c
}

func (_c *AuctionRepository_CreateAuction_Call) Return(_a0 *database.Auction, _a1 error) *AuctionRepository_CreateAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_CreateAuction_Call) RunAndReturn(run func(*database.Auction) (*database.Auction, error)) *AuctionRepository_CreateAuction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBid provides a mock function with given fields: bid
func (_m *AuctionRepository) CreateBid(bid *database.Bid) (*database.Bid, error) {
	ret := _m.Called(bid)

	if len(ret) == 0 {
		panic("no return value specified for CreateBid")
	}

	var r0 *database.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(*database.Bid) (*database.Bid, error)); ok {
		return rf(bid)
	}
	if rf, ok := ret.Get(0).(func(*database.Bid) *database.Bid); ok {
		r0 = rf(bid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(*database.Bid) error); ok {
		r1 = rf(bid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_CreateBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBid'
type AuctionRepository_CreateBid_Call struct {
	*mock.Call
}

// CreateBid is a helper method to define mock.On call
//   - bid *database.Bid
func (_e *AuctionRepository_Expecter) CreateBid(bid interface{}) *AuctionRepository_CreateBid_Call {
	return &AuctionRepository_CreateBid_Call{Call: _e.mock.On("CreateBid", bid)}
}

func (_c *AuctionRepository_CreateBid_Call) Run(run func(bid *database.Bid)) *AuctionRepository_CreateBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*database.Bid))
	})
	return _c
}

func (_c *AuctionRepository_CreateBid_Call) Return(_a0 *database.Bid, _a1 error) *AuctionRepository_CreateBid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_CreateBid_Call) RunAndReturn(run func(*database.Bid) (*database.Bid, error)) *AuctionRepository_CreateBid_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuctionById provides a mock function with given fields: id
func (_m *AuctionRepository) GetAuctionById(id uuid.UUID) (*database.Auction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuctionById")
	}

	var r0 *database.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*database.Auction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *database.Auction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_GetAuctionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuctionById'
type AuctionRepository_GetAuctionById_Call struct {
	*mock.Call
}

// GetAuctionById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *AuctionRepository_Expecter) GetAuctionById(id interface{}) *AuctionRepository_GetAuctionById_Call {
	return &AuctionRepository_GetAuctionById_Call{Call: _e.mock.On("GetAuctionById", id)}
}

func (_c *AuctionRepository_GetAuctionById_Call) Run(run func(id uuid.UUID)) *AuctionRepository_GetAuctionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_GetAuctionById_Call) Return(_a0 *database.Auction, _a1 error) *AuctionRepository_GetAuctionById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_GetAuctionById_Call) RunAndReturn(run func(uuid.UUID) (*database.Auction, error)) *AuctionRepository_GetAuctionById_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBidForAuction provides a mock function with given fields: auctionID
func (_m *AuctionRepository) GetHighestBidForAuction(auctionID uuid.UUID) (*database.Bid, error) {
	ret := _m.Called(auctionID)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBidForAuction")
	}

	var r0 *database.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*database.Bid, error)); ok {
		return rf(auctionID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *database.Bid); ok {
		r0 = rf(auctionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_GetHighestBidForAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBidForAuction'
type AuctionRepository_GetHighestBidForAuction_Call struct {
	*mock.Call
}

// GetHighestBidForAuction is a helper method to define mock.On call
//   - auctionID uuid.UUID
func (_e *AuctionRepository_Expecter) GetHighestBidForAuction(auctionID interface{}) *AuctionRepository_GetHighestBidForAuction_Call {
	return &AuctionRepository_GetHighestBidForAuction_Call{Call: _e.mock.On("GetHighestBidForAuction", auctionID)}
}

func (_c *AuctionRepository_GetHighestBidForAuction_Call) Run(run func(auctionID uuid.UUID)) *AuctionRepository_GetHighestBidForAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_GetHighestBidForAuction_Call) Return(_a0 *database.Bid, _a1 error) *AuctionRepository_GetHighestBidForAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_GetHighestBidForAuction_Call) RunAndReturn(run func(uuid.UUID) (*database.Bid, error)) *AuctionRepository_GetHighestBidForAuction_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: id
func (_m *AuctionRepository) GetUserById(id uuid.UUID) (*database.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*database.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *database.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type AuctionRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *AuctionRepository_Expecter) GetUserById(id interface{}) *AuctionRepository_GetUserById_Call {
	return &AuctionRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", id)}
}

func (_c *AuctionRepository_GetUserById_Call) Run(run func(id uuid.UUID)) *AuctionRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *AuctionRepository_GetUserById_Call) Return(_a0 *database.User, _a1 error) *AuctionRepository_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_GetUserById_Call) RunAndReturn(run func(uuid.UUID) (*database.User, error)) *AuctionRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuctions provides a mock function with no fields
func (_m *AuctionRepository) ListAuctions() ([]database.Auction, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAuctions")
	}

	var r0 []database.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]database.Auction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []database.Auction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionRepository_ListAuctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuctions'
type AuctionRepository_ListAuctions_Call struct {
	*mock.Call
}

// ListAuctions is a helper method to define mock.On call
func (_e *AuctionRepository_Expecter) ListAuctions() *AuctionRepository_ListAuctions_Call {
	return &AuctionRepository_ListAuctions_Call{Call: _e.mock.On("ListAuctions")}
}

func (_c *AuctionRepository_ListAuctions_Call) Run(run func()) *AuctionRepository_ListAuctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuctionRepository_ListAuctions_Call) Return(_a0 []database.Auction, _a1 error) *AuctionRepository_ListAuctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionRepository_ListAuctions_Call) RunAndReturn(run func() ([]database.Auction, error)) *AuctionRepository_ListAuctions_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionRepository creates a new instance of AuctionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionRepository {
	mock := &AuctionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
