// Code generated by mockery. DO NOT EDIT.

package handlers

import (
	database "auction-api/database"

	mock "github.com/stretchr/testify/mock"

	service "auction-api/service"
)

// AuctionService is an autogenerated mock type for the AuctionService type
type AuctionService struct {
	mock.Mock
}

type AuctionService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuctionService) EXPECT() *AuctionService_Expecter {
	return &AuctionService_Expecter{mock: &_m.Mock}
}

// CreateAuction provides a mock function with given fields: req
func (_m *AuctionService) CreateAuction(req *service.CreateAuctionRequest) (*database.Auction, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuction")
	}

	var r0 *database.Auction
	var r1 error
	if rf, ok := ret.Get(0).(func(*service.CreateAuctionRequest) (*database.Auction, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*service.CreateAuctionRequest) *database.Auction); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Auction)
		}
	}

	if rf, ok := ret.Get(1).(func(*service.CreateAuctionRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionService_CreateAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuction'
type AuctionService_CreateAuction_Call struct {
	*mock.Call
}

// CreateAuction is a helper method to define mock.On call
//   - req *service.CreateAuctionRequest
func (_e *AuctionService_Expecter) CreateAuction(req interface{}) *AuctionService_CreateAuction_Call {
	return &AuctionService_CreateAuction_Call{Call: _e.mock.On("CreateAuction", req)}
}

func (_c *AuctionService_CreateAuction_Call) Run(run func(req *service.CreateAuctionRequest)) *AuctionService_CreateAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*service.CreateAuctionRequest))
	})
	return _c
}

func (_c *AuctionService_CreateAuction_Call) Return(_a0 *database.Auction, _a1 error) *AuctionService_CreateAuction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionService_CreateAuction_Call) RunAndReturn(run func(*service.CreateAuctionRequest) (*database.Auction, error)) *AuctionService_CreateAuction_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBid provides a mock function with given fields: req
func (_m *AuctionService) CreateBid(req *service.CreateBidRequest) (*database.Bid, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBid")
	}

	var r0 *database.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(*service.CreateBidRequest) (*database.Bid, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*service.CreateBidRequest) *database.Bid); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Bid)
		}
	}

	if rf, ok := ret.Get(1).(func(*service.CreateBidRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuctionService_CreateBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBid'
type AuctionService_CreateBid_Call struct {
	*mock.Call
}

// CreateBid is a helper method to define mock.On call
//   - req *service.CreateBidRequest
func (_e *AuctionService_Expecter) CreateBid(req interface{}) *AuctionService_CreateBid_Call {
	return &AuctionService_CreateBid_Call{Call: _e.mock.On("CreateBid", req)}
}

func (_c *AuctionService_CreateBid_Call) Run(run func(req *service.CreateBidRequest)) *AuctionService_CreateBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*service.CreateBidRequest))
	})
	return _c
}

func (_c *AuctionService_CreateBid_Call) Return(_a0 *database.Bid, _a1 error) *AuctionService_CreateBid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuctionService_CreateBid_Call) RunAndReturn(run func(*service.CreateBidRequest) (*database.Bid, error)) *AuctionService_CreateBid_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuctionService creates a new instance of AuctionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionService {
	mock := &AuctionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
